version: "2"
services:
  application:
    container_name: red_tetris_app
    build: .
    restart: always
    volumes:
      - ./:/var/html/app/red_tetris
      - /var/html/app/red_tetris/node_modules
    ports:
      - 80:80
    links: 
      - "database"
  database:
    container_name: red_tetris_mongo
    image: mongo
    restart: always
    volumes:
      - redtetrisdata:/data/db
    ports:
      - "27017:27017"
volumes:
  redtetrisdata: